version: "3.7"

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata/var/lib/postgresql/data
      network_mode: host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ipsdb
      
  app:
    build: .
    container_name: apilist
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app

    network_mode: host


volumes:
  pgdata:
    driver: local